#!/bin/bash

#to add it to crontab run following command
#crontab 0 0 * * * ~/git/init/scripts/04

sumfile=~/.sumfile
cronefile=/etc/crontab
if [ ! -z "$sumfile" ];
then
	md5sum "$cronefile" > "$sumfile"
fi
if ! md5sum -c --status "$sumfile"; then
	echo crontab was modified | mail -s "Crontab modified" root
	md5sum "$cronefile" > "$sumfile"
fi
